<?php
/**
 * 凯拓软件 [临渊羡鱼不如退而结网,凯拓与你一同成长]
 * Project: movie-film-server
 * Date: 2022/6/11 02:05
 * Author: sleep <sleep@kaituocn.com>
 */

$json = '{
"title":"tppv2 响应报文",
"res":{
"returnCode":0,
"returnValue":{
"planSiteStates":[
{
"seatNo":"0001#0001",
"seatRow":"1",
"seatCol":"1",
"graphRow":"3",
"graphCol":"8",
"seatType":"N",
"seatState":-1,
"areaId":"0"
},
{
"seatNo":"0002#0001",
"seatRow":"2",
"seatCol":"1",
"graphRow":"4",
"graphCol":"8",
"seatType":"N",
"seatState":-1,
"areaId":"0"
},
{
"seatNo":"0003#0001",
"seatRow":"3",
"seatCol":"1",
"graphRow":"5",
"graphCol":"8",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0004#0001",
"seatRow":"4",
"seatCol":"1",
"graphRow":"6",
"graphCol":"8",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0005#0001",
"seatRow":"5",
"seatCol":"1",
"graphRow":"7",
"graphCol":"8",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0006#0001",
"seatRow":"6",
"seatCol":"1",
"graphRow":"8",
"graphCol":"8",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0007#0001",
"seatRow":"7",
"seatCol":"1",
"graphRow":"9",
"graphCol":"8",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0008#0001",
"seatRow":"8",
"seatCol":"1",
"graphRow":"10",
"graphCol":"8",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0001#0002",
"seatRow":"1",
"seatCol":"2",
"graphRow":"3",
"graphCol":"9",
"seatType":"N",
"seatState":-1,
"areaId":"0"
},
{
"seatNo":"0002#0002",
"seatRow":"2",
"seatCol":"2",
"graphRow":"4",
"graphCol":"9",
"seatType":"N",
"seatState":-1,
"areaId":"0"
},
{
"seatNo":"0003#0002",
"seatRow":"3",
"seatCol":"2",
"graphRow":"5",
"graphCol":"9",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0004#0002",
"seatRow":"4",
"seatCol":"2",
"graphRow":"6",
"graphCol":"9",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0005#0002",
"seatRow":"5",
"seatCol":"2",
"graphRow":"7",
"graphCol":"9",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0006#0002",
"seatRow":"6",
"seatCol":"2",
"graphRow":"8",
"graphCol":"9",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0007#0002",
"seatRow":"7",
"seatCol":"2",
"graphRow":"9",
"graphCol":"9",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0008#0002",
"seatRow":"8",
"seatCol":"2",
"graphRow":"10",
"graphCol":"9",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0001#0003",
"seatRow":"1",
"seatCol":"3",
"graphRow":"3",
"graphCol":"10",
"seatType":"N",
"seatState":-1,
"areaId":"0"
},
{
"seatNo":"0002#0003",
"seatRow":"2",
"seatCol":"3",
"graphRow":"4",
"graphCol":"10",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0003#0003",
"seatRow":"3",
"seatCol":"3",
"graphRow":"5",
"graphCol":"10",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0004#0003",
"seatRow":"4",
"seatCol":"3",
"graphRow":"6",
"graphCol":"10",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0005#0003",
"seatRow":"5",
"seatCol":"3",
"graphRow":"7",
"graphCol":"10",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0006#0003",
"seatRow":"6",
"seatCol":"3",
"graphRow":"8",
"graphCol":"10",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0007#0003",
"seatRow":"7",
"seatCol":"3",
"graphRow":"9",
"graphCol":"10",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0008#0003",
"seatRow":"8",
"seatCol":"3",
"graphRow":"10",
"graphCol":"10",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0001#0004",
"seatRow":"1",
"seatCol":"4",
"graphRow":"3",
"graphCol":"11",
"seatType":"N",
"seatState":-1,
"areaId":"0"
},
{
"seatNo":"0002#0004",
"seatRow":"2",
"seatCol":"4",
"graphRow":"4",
"graphCol":"11",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0003#0004",
"seatRow":"3",
"seatCol":"4",
"graphRow":"5",
"graphCol":"11",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0004#0004",
"seatRow":"4",
"seatCol":"4",
"graphRow":"6",
"graphCol":"11",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0005#0004",
"seatRow":"5",
"seatCol":"4",
"graphRow":"7",
"graphCol":"11",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0006#0004",
"seatRow":"6",
"seatCol":"4",
"graphRow":"8",
"graphCol":"11",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0007#0004",
"seatRow":"7",
"seatCol":"4",
"graphRow":"9",
"graphCol":"11",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0008#0004",
"seatRow":"8",
"seatCol":"4",
"graphRow":"10",
"graphCol":"11",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0001#0005",
"seatRow":"1",
"seatCol":"5",
"graphRow":"3",
"graphCol":"12",
"seatType":"N",
"seatState":-1,
"areaId":"0"
},
{
"seatNo":"0002#0005",
"seatRow":"2",
"seatCol":"5",
"graphRow":"4",
"graphCol":"12",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0003#0005",
"seatRow":"3",
"seatCol":"5",
"graphRow":"5",
"graphCol":"12",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0004#0005",
"seatRow":"4",
"seatCol":"5",
"graphRow":"6",
"graphCol":"12",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0005#0005",
"seatRow":"5",
"seatCol":"5",
"graphRow":"7",
"graphCol":"12",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0006#0005",
"seatRow":"6",
"seatCol":"5",
"graphRow":"8",
"graphCol":"12",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0007#0005",
"seatRow":"7",
"seatCol":"5",
"graphRow":"9",
"graphCol":"12",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0008#0005",
"seatRow":"8",
"seatCol":"5",
"graphRow":"10",
"graphCol":"12",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0001#0006",
"seatRow":"1",
"seatCol":"6",
"graphRow":"3",
"graphCol":"13",
"seatType":"N",
"seatState":-1,
"areaId":"0"
},
{
"seatNo":"0002#0006",
"seatRow":"2",
"seatCol":"6",
"graphRow":"4",
"graphCol":"13",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0003#0006",
"seatRow":"3",
"seatCol":"6",
"graphRow":"5",
"graphCol":"13",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0004#0006",
"seatRow":"4",
"seatCol":"6",
"graphRow":"6",
"graphCol":"13",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0005#0006",
"seatRow":"5",
"seatCol":"6",
"graphRow":"7",
"graphCol":"13",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0006#0006",
"seatRow":"6",
"seatCol":"6",
"graphRow":"8",
"graphCol":"13",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0007#0006",
"seatRow":"7",
"seatCol":"6",
"graphRow":"9",
"graphCol":"13",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0008#0006",
"seatRow":"8",
"seatCol":"6",
"graphRow":"10",
"graphCol":"13",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0001#0007",
"seatRow":"1",
"seatCol":"7",
"graphRow":"3",
"graphCol":"14",
"seatType":"N",
"seatState":-1,
"areaId":"0"
},
{
"seatNo":"0002#0007",
"seatRow":"2",
"seatCol":"7",
"graphRow":"4",
"graphCol":"14",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0003#0007",
"seatRow":"3",
"seatCol":"7",
"graphRow":"5",
"graphCol":"14",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0004#0007",
"seatRow":"4",
"seatCol":"7",
"graphRow":"6",
"graphCol":"14",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0005#0007",
"seatRow":"5",
"seatCol":"7",
"graphRow":"7",
"graphCol":"14",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0006#0007",
"seatRow":"6",
"seatCol":"7",
"graphRow":"8",
"graphCol":"14",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0007#0007",
"seatRow":"7",
"seatCol":"7",
"graphRow":"9",
"graphCol":"14",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0008#0007",
"seatRow":"8",
"seatCol":"7",
"graphRow":"10",
"graphCol":"14",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"graphRow":"3",
"graphCol":"15",
"seatState":2
},
{
"graphRow":"4",
"graphCol":"15",
"seatState":2
},
{
"graphRow":"5",
"graphCol":"15",
"seatState":2
},
{
"graphRow":"6",
"graphCol":"15",
"seatState":2
},
{
"graphRow":"7",
"graphCol":"15",
"seatState":2
},
{
"graphRow":"8",
"graphCol":"15",
"seatState":2
},
{
"graphRow":"9",
"graphCol":"15",
"seatState":2
},
{
"seatNo":"0008#0008",
"seatRow":"8",
"seatCol":"8",
"graphRow":"10",
"graphCol":"15",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0001#0008",
"seatRow":"1",
"seatCol":"8",
"graphRow":"3",
"graphCol":"16",
"seatType":"N",
"seatState":-1,
"areaId":"0"
},
{
"seatNo":"0002#0008",
"seatRow":"2",
"seatCol":"8",
"graphRow":"4",
"graphCol":"16",
"seatType":"N",
"seatState":-1,
"areaId":"0"
},
{
"seatNo":"0003#0008",
"seatRow":"3",
"seatCol":"8",
"graphRow":"5",
"graphCol":"16",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0004#0008",
"seatRow":"4",
"seatCol":"8",
"graphRow":"6",
"graphCol":"16",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0005#0008",
"seatRow":"5",
"seatCol":"8",
"graphRow":"7",
"graphCol":"16",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0006#0008",
"seatRow":"6",
"seatCol":"8",
"graphRow":"8",
"graphCol":"16",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0007#0009",
"seatRow":"7",
"seatCol":"9",
"graphRow":"9",
"graphCol":"16",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"graphRow":"10",
"graphCol":"16",
"seatState":2
},
{
"seatNo":"0001#0009",
"seatRow":"1",
"seatCol":"9",
"graphRow":"3",
"graphCol":"17",
"seatType":"N",
"seatState":-1,
"areaId":"0"
},
{
"seatNo":"0002#0009",
"seatRow":"2",
"seatCol":"9",
"graphRow":"4",
"graphCol":"17",
"seatType":"N",
"seatState":-1,
"areaId":"0"
},
{
"seatNo":"0003#0009",
"seatRow":"3",
"seatCol":"9",
"graphRow":"5",
"graphCol":"17",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0004#0009",
"seatRow":"4",
"seatCol":"9",
"graphRow":"6",
"graphCol":"17",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0005#0009",
"seatRow":"5",
"seatCol":"9",
"graphRow":"7",
"graphCol":"17",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0006#0009",
"seatRow":"6",
"seatCol":"9",
"graphRow":"8",
"graphCol":"17",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"seatNo":"0007#0010",
"seatRow":"7",
"seatCol":"10",
"graphRow":"9",
"graphCol":"17",
"seatType":"N",
"seatState":0,
"areaId":"0"
},
{
"graphRow":"10",
"graphCol":"17",
"seatState":2
}
]
}
}
}';

$arr = json_decode($json, true)['res']['returnValue'];
var_dump(json_encode(setTppSeat($arr)['sections']));


function setTppSeat($data)
{
    $data       = $data['planSiteStates'];
    $sectionIds = [];
    //计算最大行数和列数
    $xs = array_column($data, 'graphRow');//座位横坐标
    $ys = array_column($data, 'graphCol');//座位纵坐标

    $max_rows = intval(max($xs));
    $max_cols = intval(max($ys));
    $minX     = intval(min($xs));
    $minY     = intval(min($ys));
    //定义座位信息重组
    $seat = [];
    foreach ($data as $k => $datum) {
        if ($datum['seatState'] != 2) {
            $sectionIds[$datum['areaId']] = $datum['areaId'];
        }
    }
    $sections = [];
    foreach ($sectionIds as $sectionId) {
        $a = 0;
        for ($i = $minX; $i <= $max_rows; $i++) {
            $seat[$a]['row_name'] = $i - $minX + 1;      //座位横坐标
            $seat[$a]['row_id']   = $i - $minX + 1;      //座位横坐标
            //遍历列信息
            $b = 0;
            for ($j = $minY; $j <= $max_cols; $j++) {
                $columns = [
                    'area_id'   => $sectionId,
                    'area_name' => $sectionId,
                    'column_id' => null,
                    'seat_no'   => null,
                    'seat_row'  => null,
                    'state'     => "N",
                    'type'      => 'N'
                ];
                foreach ($data as $ssk => $ssv) {
                    if ($ssv['seatState'] == 2) {
                        //过道
                        continue;
                    }
                    if ($ssv['graphRow'] == $i && $ssv['graphCol'] == $j) {
                        //座区类型 L:情侣座左 R：情侣座右 N:普通座
                        switch ($ssv['seatType']) {
                            case 'L':
                            case 'R':
                                $type = $ssv['seatType'];
                                break;
                            case 'N':
                            default:
                                $type = 'E';
                                break;
                        }
                        $seatNo = [
                            $ssv['areaId'],
                            $ssv['seatNo'],
                            $ssv['graphRow'],
                            $ssv['graphCol'],
                            $ssv['seatRow'] . '排' . $ssv['seatCol'] . '座',
                        ];
                        //状态 (-1 不可售 0-可售 2-过道)
                        switch ($ssv['seatState']) {
                            case -1:
                                $status = 'N';
                                break;
                            case 0:
                                $status = 'Y';
                                break;
                            case 2:
                            default:
                                $status = 'N';
//                                $type   = 'N';
                                break;
                        }
                        if ($sectionId == $ssv['areaId']) {
                            $columns = [
                                'area_id'   => $ssv['areaId'],
                                'area_name' => $seat[$a]['row_name'],
                                'column_id' => $ssv['seatCol'],
                                //座位列号
                                'seat_no'   => implode('_', $seatNo),
                                'seat_row'  => $ssv['seatRow'],
                                //座位排号
                                'state'     => $status,
                                'type'      => $type,
                            ];
                        }
                    }
                }
                $seat[$a]['columns'][$b] = $columns;
                $b++;
            }
            $a++;
        }
        $sections['sections'][] = [
            'cols'         => $max_cols - $minY + 1,             //最大列
            'rows'         => $max_rows - $minX + 1,             //最大行
            'section_id'   => (string)$sectionId,    //影厅区域ID
            'section_name' => "",                    //影厅区域名称
            'seat'         => $seat,                 //最为数组
        ];
    }
//        foreach ($sections['sections'] as $ok => $ov) {
//            $array = $ov['seat'];
//            array_multisort(array_column($array, 'row_id'), SORT_ASC, $array);
//            $sections['sections'][$ok]['seat'] = $array;
//        }
    return $sections;
}
